// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: url_shortener.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UrlShortenerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UrlPath       string                 `protobuf:"bytes,1,opt,name=url_path,json=urlPath,proto3" json:"url_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UrlShortenerRequest) Reset() {
	*x = UrlShortenerRequest{}
	mi := &file_url_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UrlShortenerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlShortenerRequest) ProtoMessage() {}

func (x *UrlShortenerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlShortenerRequest.ProtoReflect.Descriptor instead.
func (*UrlShortenerRequest) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *UrlShortenerRequest) GetUrlPath() string {
	if x != nil {
		return x.UrlPath
	}
	return ""
}

type SetUrlShorteneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUrlShorteneResponse) Reset() {
	*x = SetUrlShorteneResponse{}
	mi := &file_url_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUrlShorteneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUrlShorteneResponse) ProtoMessage() {}

func (x *SetUrlShorteneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUrlShorteneResponse.ProtoReflect.Descriptor instead.
func (*SetUrlShorteneResponse) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *SetUrlShorteneResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_url_shortener_proto protoreflect.FileDescriptor

const file_url_shortener_proto_rawDesc = "" +
	"\n" +
	"\x13url_shortener.proto\x12\x05proto\"0\n" +
	"\x13UrlShortenerRequest\x12\x19\n" +
	"\burl_path\x18\x01 \x01(\tR\aurlPath\"0\n" +
	"\x16SetUrlShorteneResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2c\n" +
	"\x13UrlShortenerService\x12L\n" +
	"\x0fAddUrlShortener\x12\x1a.proto.UrlShortenerRequest\x1a\x1d.proto.SetUrlShorteneResponseB\x04Z\x02./b\x06proto3"

var (
	file_url_shortener_proto_rawDescOnce sync.Once
	file_url_shortener_proto_rawDescData []byte
)

func file_url_shortener_proto_rawDescGZIP() []byte {
	file_url_shortener_proto_rawDescOnce.Do(func() {
		file_url_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_url_shortener_proto_rawDesc), len(file_url_shortener_proto_rawDesc)))
	})
	return file_url_shortener_proto_rawDescData
}

var file_url_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_url_shortener_proto_goTypes = []any{
	(*UrlShortenerRequest)(nil),    // 0: proto.UrlShortenerRequest
	(*SetUrlShorteneResponse)(nil), // 1: proto.SetUrlShorteneResponse
}
var file_url_shortener_proto_depIdxs = []int32{
	0, // 0: proto.UrlShortenerService.AddUrlShortener:input_type -> proto.UrlShortenerRequest
	1, // 1: proto.UrlShortenerService.AddUrlShortener:output_type -> proto.SetUrlShorteneResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_url_shortener_proto_init() }
func file_url_shortener_proto_init() {
	if File_url_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_url_shortener_proto_rawDesc), len(file_url_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_url_shortener_proto_goTypes,
		DependencyIndexes: file_url_shortener_proto_depIdxs,
		MessageInfos:      file_url_shortener_proto_msgTypes,
	}.Build()
	File_url_shortener_proto = out.File
	file_url_shortener_proto_goTypes = nil
	file_url_shortener_proto_depIdxs = nil
}
