// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: url_shortener.proto

package __

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddUrlShortenerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UrlPath       string                 `protobuf:"bytes,1,opt,name=url_path,json=urlPath,proto3" json:"url_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUrlShortenerRequest) Reset() {
	*x = AddUrlShortenerRequest{}
	mi := &file_url_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUrlShortenerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUrlShortenerRequest) ProtoMessage() {}

func (x *AddUrlShortenerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUrlShortenerRequest.ProtoReflect.Descriptor instead.
func (*AddUrlShortenerRequest) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *AddUrlShortenerRequest) GetUrlPath() string {
	if x != nil {
		return x.UrlPath
	}
	return ""
}

type UrlShortener struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UrlPath       string                 `protobuf:"bytes,2,opt,name=url_path,json=urlPath,proto3" json:"url_path,omitempty"`
	Shortcut      string                 `protobuf:"bytes,3,opt,name=shortcut,proto3" json:"shortcut,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UrlShortener) Reset() {
	*x = UrlShortener{}
	mi := &file_url_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UrlShortener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlShortener) ProtoMessage() {}

func (x *UrlShortener) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlShortener.ProtoReflect.Descriptor instead.
func (*UrlShortener) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *UrlShortener) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UrlShortener) GetUrlPath() string {
	if x != nil {
		return x.UrlPath
	}
	return ""
}

func (x *UrlShortener) GetShortcut() string {
	if x != nil {
		return x.Shortcut
	}
	return ""
}

type AddUrlShorteneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUrlShorteneResponse) Reset() {
	*x = AddUrlShorteneResponse{}
	mi := &file_url_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUrlShorteneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUrlShorteneResponse) ProtoMessage() {}

func (x *AddUrlShorteneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUrlShorteneResponse.ProtoReflect.Descriptor instead.
func (*AddUrlShorteneResponse) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *AddUrlShorteneResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_url_shortener_proto protoreflect.FileDescriptor

const file_url_shortener_proto_rawDesc = "" +
	"\n" +
	"\x13url_shortener.proto\x12\x05proto\"3\n" +
	"\x16AddUrlShortenerRequest\x12\x19\n" +
	"\burl_path\x18\x01 \x01(\tR\aurlPath\"U\n" +
	"\fUrlShortener\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\burl_path\x18\x02 \x01(\tR\aurlPath\x12\x1a\n" +
	"\bshortcut\x18\x03 \x01(\tR\bshortcut\"0\n" +
	"\x16AddUrlShorteneResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2f\n" +
	"\x13UrlShortenerService\x12O\n" +
	"\x0fAddUrlShortener\x12\x1d.proto.AddUrlShortenerRequest\x1a\x1d.proto.AddUrlShorteneResponseB\x04Z\x02./b\x06proto3"

var (
	file_url_shortener_proto_rawDescOnce sync.Once
	file_url_shortener_proto_rawDescData []byte
)

func file_url_shortener_proto_rawDescGZIP() []byte {
	file_url_shortener_proto_rawDescOnce.Do(func() {
		file_url_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_url_shortener_proto_rawDesc), len(file_url_shortener_proto_rawDesc)))
	})
	return file_url_shortener_proto_rawDescData
}

var file_url_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_url_shortener_proto_goTypes = []any{
	(*AddUrlShortenerRequest)(nil), // 0: proto.AddUrlShortenerRequest
	(*UrlShortener)(nil),           // 1: proto.UrlShortener
	(*AddUrlShorteneResponse)(nil), // 2: proto.AddUrlShorteneResponse
}
var file_url_shortener_proto_depIdxs = []int32{
	0, // 0: proto.UrlShortenerService.AddUrlShortener:input_type -> proto.AddUrlShortenerRequest
	2, // 1: proto.UrlShortenerService.AddUrlShortener:output_type -> proto.AddUrlShorteneResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_url_shortener_proto_init() }
func file_url_shortener_proto_init() {
	if File_url_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_url_shortener_proto_rawDesc), len(file_url_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_url_shortener_proto_goTypes,
		DependencyIndexes: file_url_shortener_proto_depIdxs,
		MessageInfos:      file_url_shortener_proto_msgTypes,
	}.Build()
	File_url_shortener_proto = out.File
	file_url_shortener_proto_goTypes = nil
	file_url_shortener_proto_depIdxs = nil
}
